linters:
  enable-all: true
  disable:
    - gochecknoinits
    - nlreturn
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - gomnd
        - testpackage
