linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - nlreturn
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - gomnd
        - paralleltest
        - testpackage
